#%RAML 0.8
title: Together We Study
/users:
  get:
    description: Search users
    queryParameters:
      name:
        description: Search users by name
      location:
        description: Search users by location
      school:
        description: Search users by school
  /{userID}:
    post:
      description: Create new user
      body:
        application/json:
          schema: |
            { "$schema": "http://json-schema.org/schema",
              "type": "object",
              "description": "A user looking for study groups",
              
              "properties": {
                "name": { "type": "string" },
                "school": { "type": "string" },
                "location": { "type": "string" },
                "email": { "type": "string" }
              }
              "required": [ "name", "email" ]
            }
    delete:
      description: Delete a user
      
/lfg:
  get:
    description: Search study group postings
    queryParameters:
      studySubject:
        description: Search postings by study subject
        required: true
      location:
        description: Search postings by user location
      user:
        description: Search postings by user name
      startTime:
        description: Search postings by start time
      endTime:
        description: Search postings by end time
  /{lfgID}:
    post:
      description: Create a new study group posting
      body:
        application/json:
          schema: |
            { "$schema": "http://json-schema.org/schema",
              "type": "object",
              "description": "A posting for a study group",
              
              "properties": {
                "owner": { "type": "string" },
                "title": { "type": "string" },
                "studySubject": { "type": "string" },
                "startTime": { "type": "number" },
                "endTime": { "type": "number" }
              }
              "required": [ "owner", "title", "studySubject" ]
            }
    delete:
      description: Delete a study group posting