#%RAML 0.8
title: Together We Study
schemas:
  - lfg: !include schema/lfg.json
  - user: !include schema/user.json
  - userCollection: !include schema/userCollection.json
  - lfgCollection: !include schema/lfgCollection.json

/users:
  description: User accounts
    
  post:
    description: Create a new user
    queryParameters:
      userName:
        type: string
      school:
        type: string
      email:
        type: string
      location:
        type: string
    
  get:
    description: Search users
    queryParameters:
      userName:
        type: string
      school:
        type: string
      location:
        type: string
    responses:
      200:
        body:
          application/json:
            schema: userCollection
        
    
  /{userID}:
    description: A single user account
    uriParameters:
      userID:
        description: User ID
        type: integer
        
    get:
      description: View a single user by ID
      responses:
        200:
          body:
            application/json:
              schema: user

/lfg:
  description: Study group postings
  
  post:
    description: Create a new study group posting
    queryParameters:
      studySubject:
        description: What subject the posting is for
        type: string
      owner:
        description: Who is creating the posting
        type: integer
      title:
        description: The posting title
        type: string
      startTime:
        description: The starting time for the posting
        type: string
      endTime:
        description: The ending time for the posting
        type: string
      
  get:
    description: Search study group postings
    queryParameters:
      studySubject:
        description: Filter by study subject
        type: string
      owner:
        description: Filter by owner ID
        type: integer
      location:
        description: Filter by location
        type: string
      title:
        description: Filter by posting title
        type: string
      startTime:
        description: Filter by start time
        type: string
      endTime:
        description: Filter by end time
        type: string
    responses:
      200:
        body:
          application/json:
            schema: lfgCollection
        
  /{lfgID}:
    description: A posting for a study group
    uriParameters:
      lfgID:
        description: Posting ID
        type: integer
        
    get:
      description: View a single study group posting by ID
      responses:
        200:
          body:
            application/json:
              schema: lfg
    
    delete:
      description: Delete a study group posting
      
    /tweet:
      post:
        description: Tweet a study group posting (@TogetherWeStand)